FROM golang:1.15.0

RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
RUN go get github.com/go-delve/delve/cmd/dlv

WORKDIR /app

COPY ./go.* ./
RUN go mod tidy

CMD air